language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "OPQVzB18iybp46uhori2Gj6q2W0joMCFf8xwam+V02Pi4vSmY+6iwvb/sS88sHAXi+z4vPsXXIHyRMsi3yiUCCSMSTHa81qHPlZt2eMj8z+W0sUAP7U0hjrD4wm+wMBWcWRF3Og2P8YV4fNh+VTotJWwG6Kp/LhTxZMyBVvJBA2bjlBWqO9hpm4dHz3YWswdBaW+Mr9M9ftzHLxN+8tM2ZiNhVNGqq1iicv9Rxf0y7Lwvdb77oQOcQM/NYcgydRVFp1wYU09eLEw4X4Dz+N+xT4VGjEQWB3cBc6q/Lk8a34+QaZtKFwd7aVZhcIp+NDl3cAb5fX+nV0hU3ygueEYuP7Q5yj9BRY7JCP0VuaRx6T4DhXBP35J4juvwhBBNrjv5zIAuMnAQmHgWqoQwE09vfXoxzoZIARyv9tU1x1GZ3UuZjaVn9Zyu7WiA3j1HDmwJbTKb7Zh+fFADw96HEaD3dM25j64TTBJMugOtUqLlUUpBEXcVil2G+IgDNMd6e1P9ZH1IXMOH8mblj1FaFyQhf92fFjkZx5cLFsJ5XsVCdIYih/jo2Vokbm7LoYNPeHCOMIL8zPCxXM/NuoC+RlN0klP/D4cg/DhVYRIOgMYV2hIV8cjVyAxKNMdy6k6DJGK2Q9LcxvNRKDN72HvnLGldGtB8ViqWH8ZN2EmMIrn43M="
  api_key: # 85a5
    secure: "AtYlp1cRWJvqCBQSLY32Fc3mX2PKzuOFqCR2dGfSrrRZZsV3C116yj8O76br0u12YPEiLpDfQt+b/f08RxATZazpL/+hxUoGdsH4FhcUuzX/zJSelW96zUY1wH6ZJcNL99uLOZd/zrZ0wkE+alolif5/fkt78uEiDUcZW5JwrFiLXPHPKLzgU+kvhK8B2OhcvirmfouQfZ73cQL7xSgah5Mfz76b4Op6B9/Qn5Emxh4brGE0H0+3pqJwrVGePXFhAQ1ATx5ALWMLSV0IaDULXuZBT960ovk6U3zFTY0PPA+9Xv7K9lhfdPFPnIoq45GeQiyJSqpSWTaNUpvhln2/pZBRBbWonADMmtxYUB9RJ9BUpARf7X00GnhZbmM1fCLFhZaHkjS9Jt16pGdzJdq8AjnlxuOdohmE1kxUKaoQ1xyIJ0ukRlRxvfCmjEk1m2veow3aqfkmfEYJbunb5kc2CZeA2MsboioxnafRO94GkK+MG+3JiLJtWd3a9GBw3uv6/5UKRH5CBmk0+a0u22l7QBXl5Bl6abU4rMuAWpTZVER1mJQa5I13I6FwhR3hh26DX/Aep5zGRxHQh2QWPhB4wOv58APmsahvXdfNf1yrTFwHsLOHiUHWZxsKoG9dbTJFI7mg7JxkWXMtIZx3bUnqkX6JStU+RgOPtuf00drI4R0="
  on:
    tags: true
    node: lts/*
